// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"hz08tdry07","name":"SnackPacks","description":"SnackPacks Regional API Ohio","endpoint":"https://hz08tdry07.execute-api.us-east-2.amazonaws.com/prod","region":"us-east-2","paths":["/"]}],
    'aws_cognito_identity_pool_id': 'us-east-2:5632822c-c6fb-443c-9f30-6935e22e7462',
    'aws_cognito_region': 'us-east-2',
    'aws_mobile_analytics_app_id': '20d890394a124fc9a5f3f4bd56707d65',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '78a6305d-7851-49df-8817-5a9ee195ddf8',
    'aws_project_name': 'SnackPacks',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'snackpacks-mobilehub-1497259064',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_5QHOV8BID',
    'aws_user_pools_mfa_type': 'OPTIONAL',
    'aws_user_pools_web_client_id': '6r7fom15c4ieo3h6vjkk870d7i',
}

export default awsmobile;
