// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cloud_logic = 'enable';
var aws_cloud_logic_custom = [{"id":"hz08tdry07","name":"SnackPacks","description":"SnackPacks Regional API Ohio","endpoint":"https://hz08tdry07.execute-api.us-east-2.amazonaws.com/lambdaIntegration","region":"us-east-2","paths":["/admin","/admin/drivers","/drivers","/payment","/snackpacks"]}];
var aws_cognito_identity_pool_id = 'us-east-2:5632822c-c6fb-443c-9f30-6935e22e7462';
var aws_cognito_region = 'us-east-2';
var aws_mandatory_sign_in = 'enable';
var aws_mobile_analytics_app_id = '20d890394a124fc9a5f3f4bd56707d65';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '78a6305d-7851-49df-8817-5a9ee195ddf8';
var aws_project_name = 'SnackPacks';
var aws_project_region = 'us-east-2';
var aws_resource_name_prefix = 'snackpacks-mobilehub-1497259064';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-2_uJ9lx0oC2';
var aws_user_pools_web_client_id = '4n6lolojqqcik7okb0bmhrmes9';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
